window.CONTROLFLOW_DATA = {
  sourceNodes: [
    { id:"src_entry", label:"PROGRAM_ENTRY", type:"entry", children:["src_reshape","src_main_loop"] },
    { id:"src_reshape", label:"LOOP_RESHAPE", type:"loop", annotation:"for _ in loop(0,1,1)", pathRef:"PATH0_4", children:[] },
    { id:"src_main_loop", label:"IndexerPrologQuantQuantLoop", type:"loop_unroll",
      annotation:"loop_unroll(0, t, 1,\nunroll_list=[32,16,8,4,2,1])",
      children:["src_u32","src_u16","src_u8","src_u4","src_u2","src_u1"] },
    { id:"src_u32", label:"unroll ×32", type:"unroll", pathRef:"PATH0_6",  annotation:"t_tile=32" },
    { id:"src_u16", label:"unroll ×16", type:"unroll", pathRef:"PATH0_8",  annotation:"t_tile=16" },
    { id:"src_u8",  label:"unroll ×8",  type:"unroll", pathRef:"PATH0_10", annotation:"t_tile=8"  },
    { id:"src_u4",  label:"unroll ×4",  type:"unroll", pathRef:"PATH0_12", annotation:"t_tile=4"  },
    { id:"src_u2",  label:"unroll ×2",  type:"unroll", pathRef:"PATH0_14", annotation:"t_tile=2"  },
    { id:"src_u1",  label:"unroll ×1",  type:"unroll", pathRef:"PATH0_16", annotation:"t_tile=1"  },
  ],
  compiledNodes: [
    { id:"cmp_entry", label:"ControlFlowEntry", type:"entry", children:["cmp_reshape","cmp_main_loop"] },
    { id:"cmp_reshape", label:"LOOP_RESHAPE", type:"loop",
      pathId:"PATH0_4", annotation:"Unroll1 / 6 kernels", children:[] },
    { id:"cmp_main_loop", label:"IndexerPrologQuantQuantLoop", type:"loop_unroll",
      annotation:"RootStitch(1-6)", children:["cmp_p6","cmp_p8","cmp_p10","cmp_p12","cmp_p14","cmp_p16"] },
    { id:"cmp_p6",  label:"PATH0_6",  pathId:"PATH0_6",  type:"path", annotation:"step=32 / 30 kernels" },
    { id:"cmp_p8",  label:"PATH0_8",  pathId:"PATH0_8",  type:"path", annotation:"step=16 / 16 kernels" },
    { id:"cmp_p10", label:"PATH0_10", pathId:"PATH0_10", type:"path", annotation:"step=8  / 22 kernels" },
    { id:"cmp_p12", label:"PATH0_12", pathId:"PATH0_12", type:"path", annotation:"step=4  / 18 kernels" },
    { id:"cmp_p14", label:"PATH0_14", pathId:"PATH0_14", type:"path", annotation:"step=2  / 18 kernels" },
    { id:"cmp_p16", label:"PATH0_16", pathId:"PATH0_16", type:"path", annotation:"step=1  / 18 kernels" },
  ],
  mappings: [
    { from:"src_reshape", to:"cmp_reshape" },
    { from:"src_u32", to:"cmp_p6"  },
    { from:"src_u16", to:"cmp_p8"  },
    { from:"src_u8",  to:"cmp_p10" },
    { from:"src_u4",  to:"cmp_p12" },
    { from:"src_u2",  to:"cmp_p14" },
    { from:"src_u1",  to:"cmp_p16" },
  ],
};
