#!/usr/bin/env python3
"""
Generate tokens.js and tokens.json from CSS token sources.

Source of truth:
  - foundation.css
  - semantic.css
  - components.css

Do not edit generated files by hand.
"""

from __future__ import annotations

import json
import re
from collections import OrderedDict
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parent
FOUNDATION = ROOT / "foundation.css"
SEMANTIC = ROOT / "semantic.css"
COMPONENTS = ROOT / "components.css"
TOKENS_JS = ROOT / "tokens.js"
TOKENS_JSON = ROOT / "tokens.json"


BLOCK_RE = re.compile(r"(?P<selectors>[^{}]+)\{(?P<body>[^{}]*)\}", re.S)
VAR_RE = re.compile(r"(--[A-Za-z0-9_-]+)\s*:\s*([^;]+);")


def strip_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def parse_vars(path: Path) -> OrderedDict[str, OrderedDict[str, str]]:
    text = strip_comments(path.read_text(encoding="utf-8"))
    scopes: OrderedDict[str, OrderedDict[str, str]] = OrderedDict()

    for match in BLOCK_RE.finditer(text):
        selectors = " ".join(match.group("selectors").split())
        if ":root" not in selectors:
            continue

        if "data-theme='light'" in selectors:
            scope = "light"
        elif path.name == "semantic.css":
            scope = "dark"
        else:
            scope = "base"

        scope_vars = scopes.setdefault(scope, OrderedDict())
        for name, value in VAR_RE.findall(match.group("body")):
            scope_vars[name[2:]] = " ".join(value.split())

    return scopes


def merge_dicts(*dicts: OrderedDict[str, str]) -> OrderedDict[str, str]:
    merged: OrderedDict[str, str] = OrderedDict()
    for data in dicts:
        for key, value in data.items():
            merged[key] = value
    return merged


def camel_case(name: str) -> str:
    parts = re.split(r"[-_]+", name)
    if not parts:
        return name
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def build_source() -> OrderedDict[str, OrderedDict[str, OrderedDict[str, str]]]:
    return OrderedDict(
        [
            ("foundation", parse_vars(FOUNDATION)),
            ("semantic", parse_vars(SEMANTIC)),
            ("components", parse_vars(COMPONENTS)),
        ]
    )


def build_themes(source: OrderedDict[str, OrderedDict[str, OrderedDict[str, str]]]) -> OrderedDict[str, OrderedDict[str, str]]:
    foundation = source["foundation"]
    semantic = source["semantic"]
    components = source["components"]

    dark = merge_dicts(
        foundation.get("base", OrderedDict()),
        semantic.get("dark", OrderedDict()),
        components.get("base", OrderedDict()),
    )
    light = merge_dicts(
        foundation.get("base", OrderedDict()),
        foundation.get("light", OrderedDict()),
        semantic.get("light", OrderedDict()),
        components.get("base", OrderedDict()),
        components.get("light", OrderedDict()),
    )

    return OrderedDict([("dark", dark), ("light", light)])


def build_js_tokens(themes: OrderedDict[str, OrderedDict[str, str]]) -> OrderedDict[str, OrderedDict[str, str]]:
    out: OrderedDict[str, OrderedDict[str, str]] = OrderedDict()
    for theme_name, values in themes.items():
        out[theme_name] = OrderedDict((camel_case(key), value) for key, value in values.items())
    return out


def to_js(value, indent: int = 0) -> str:
    pad = " " * indent
    if isinstance(value, OrderedDict):
        lines = ["{"]
        items = list(value.items())
        for idx, (key, item) in enumerate(items):
            comma = "," if idx < len(items) - 1 else ""
            lines.append(f'{pad}  "{key}": {to_js(item, indent + 2)}{comma}')
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(value, dict):
        return to_js(OrderedDict(value), indent)
    if isinstance(value, list):
        inner = ", ".join(to_js(item, indent) for item in value)
        return f"[{inner}]"
    return json.dumps(value, ensure_ascii=False)


def write_tokens_js(source, themes, js_tokens) -> None:
    content = f"""/**
 * AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Source of truth:
 *   - tokens/foundation.css
 *   - tokens/semantic.css
 *   - tokens/components.css
 * Generated by:
 *   - tokens/generate_tokens.py
 */

export const PTO_TOKEN_SOURCE = {to_js(source, 0)};

export const PTO_THEME_VARS = {to_js(themes, 0)};

export const PTO_TOKENS = {to_js(js_tokens, 0)};

/** Shorthand: current default theme tokens */
export const t = PTO_TOKENS.dark;
"""
    TOKENS_JS.write_text(content + "\n", encoding="utf-8")


def write_tokens_json(source, themes) -> None:
    payload = OrderedDict(
        [
            (
                "$meta",
                OrderedDict(
                    [
                        ("version", "2.0.0"),
                        ("generated", str(date.today())),
                        ("generator", "tokens/generate_tokens.py"),
                        ("sourceOfTruth", ["tokens/foundation.css", "tokens/semantic.css", "tokens/components.css"]),
                        ("editPolicy", "Edit CSS token sources, then rerun the generator. Do not edit this file by hand."),
                    ]
                ),
            ),
            ("source", source),
            ("themes", themes),
        ]
    )
    TOKENS_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    source = build_source()
    themes = build_themes(source)
    js_tokens = build_js_tokens(themes)
    write_tokens_js(source, themes, js_tokens)
    write_tokens_json(source, themes)
    print(f"Generated {TOKENS_JS.relative_to(ROOT.parent)} and {TOKENS_JSON.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
